
import { Facility } from './types';

export const NAGA_FACILITIES: Facility[] = [
  {
    id: 'cho-1',
    name: 'Naga City Health Office I',
    type: 'Clinic',
    services: ['Specialized Consultation', 'Laboratory', 'Radiology', 'Pharmacy', 'Dental'],
    specializedServices: ['Animal Bite Center', 'TB-DOTS Main', 'Social Hygiene Clinic', 'Mental Health Hub'],
    contactPersonnel: 'Dr. John Bongat (CHO)',
    philHealthSupported: true,
    distanceKm: 0.2,
    baseCost: 'Low',
    currentCongestion: 70,
    waitingTimeMinutes: 45,
    contactNumber: '(054) 881 0447',
    operatingHours: 'Mon-Fri 8AM-5PM',
    location: { lat: 13.6218, lng: 123.1841 }
  },
  {
    id: 'cho-2',
    name: 'Naga City Health Office II',
    type: 'Clinic',
    services: ['General Consultation', 'Maternal & Child Health', 'Laboratory', 'Nutrition'],
    specializedServices: ['Animal Bite Center', 'TB-DOTS', 'Family Planning Center'],
    contactPersonnel: 'CHO II Staff',
    philHealthSupported: true,
    distanceKm: 3.2,
    baseCost: 'Low',
    currentCongestion: 50,
    waitingTimeMinutes: 30,
    contactNumber: '(054) 472 0184',
    operatingHours: 'Mon-Fri 8AM-5PM',
    location: { lat: 13.6158, lng: 123.2191 }
  },
  {
    id: 'ncgh-1',
    name: 'Naga City General Hospital',
    type: 'Public Hospital',
    services: ['Emergency', 'Pediatrics', 'Obstetrics', 'Laboratory', 'Specialist Care'],
    philHealthSupported: true,
    distanceKm: 2.5,
    baseCost: 'Low',
    currentCongestion: 85,
    waitingTimeMinutes: 120,
    contactNumber: '0917-314-8740',
    operatingHours: '24/7 (Emergency)',
    location: { lat: 13.6218, lng: 123.1841 }
  },
  {
    id: 'bhs-abella',
    name: 'Abella Barangay Health Station',
    type: 'BHC',
    services: ['Daily Consultation', 'Family Planning', 'Nutrition', 'Immunization', 'Prenatal'],
    specializedServices: ['Adolescent Health', 'Mental Health', 'Women\'s Health (VIA)', 'Medical Check-up', 'Dental Check-up'],
    contactPersonnel: 'Stephanie Mae C. Magistrado (MW)',
    philHealthSupported: true,
    distanceKm: 1.2,
    baseCost: 'Free',
    currentCongestion: 30,
    waitingTimeMinutes: 15,
    contactNumber: '0961-995-0058',
    operatingHours: 'Mon-Fri 8AM-5PM',
    location: { lat: 13.6248, lng: 123.1891 }
  },
  {
    id: 'bhs-bagumbayan-norte',
    name: 'Bagumbayan Norte BHS',
    type: 'BHC',
    services: ['Daily Consultation', 'Family Planning', 'NCD Risk Assessment', 'Immunization', 'Prenatal'],
    specializedServices: ['PSI Insertion/Removal', 'Dental Check-up'],
    contactPersonnel: 'Sarah Kay S. Cano (MW)',
    philHealthSupported: true,
    distanceKm: 1.5,
    baseCost: 'Free',
    currentCongestion: 25,
    waitingTimeMinutes: 20,
    contactNumber: '0963-758-9088',
    operatingHours: 'Mon-Fri 8AM-5PM',
    location: { lat: 13.6308, lng: 123.1901 }
  },
  {
    id: 'bhs-bagumbayan-sur',
    name: 'Bagumbayan Sur BHS',
    type: 'BHC',
    services: ['Daily Consultation', 'Family Planning', 'NTP Dispensing', 'YAKAP Profiling', 'Risk Assessment'],
    specializedServices: ['PSI Insertion', 'Mobile Blood Donation', 'Operation Tuli', 'Basic Oral Health', 'HPV Immunization'],
    contactPersonnel: 'Gemma R. Paglinawan (MW)',
    philHealthSupported: true,
    distanceKm: 2.1,
    baseCost: 'Free',
    currentCongestion: 45,
    waitingTimeMinutes: 30,
    contactNumber: '0916-823-9471',
    operatingHours: 'Mon-Fri 8AM-5PM',
    location: { lat: 13.6288, lng: 123.2081 }
  },
  {
    id: 'bhs-balatas',
    name: 'Balatas Barangay Health Station',
    type: 'BHC',
    services: ['Daily Consultation', 'Family Planning', 'NTP', 'Prenatal Day', 'Immunization'],
    specializedServices: ['Adolescent Health', 'Dental Check-up', 'NCD Risk Assessment'],
    contactPersonnel: 'Mariel San Agustin (MW)',
    philHealthSupported: true,
    distanceKm: 1.8,
    baseCost: 'Free',
    currentCongestion: 35,
    waitingTimeMinutes: 25,
    contactNumber: '0950-868-2736',
    operatingHours: 'Mon-Fri 8AM-5PM',
    location: { lat: 13.6358, lng: 123.2041 }
  },
  {
    id: 'bhs-calauag',
    name: 'Calauag Barangay Health Station',
    type: 'BHC',
    services: ['Adolescent Health Program', 'Prenatal Services', 'Immunization', 'NTP'],
    specializedServices: ['VIA Screening', 'Blood Donation', 'Operation Tuli', 'Dog Vaccination', 'Flu Vaccination'],
    contactPersonnel: 'Rowena F. Reondanga (MW)',
    philHealthSupported: true,
    distanceKm: 3.5,
    baseCost: 'Free',
    currentCongestion: 15,
    waitingTimeMinutes: 10,
    contactNumber: '0910-153-7273',
    operatingHours: 'Mon-Fri 8AM-5PM',
    location: { lat: 13.6458, lng: 123.2141 }
  },
  {
    id: 'bhs-cararayan',
    name: 'Cararayan Barangay Health Station',
    type: 'BHC',
    services: ['Family Planning (DMPA)', 'Prenatal Day', 'Immunization', 'NTP/TB PT'],
    specializedServices: ['Adolescent Counseling', 'PSI Insertion', 'Nutritional Monitoring (4Ps)'],
    contactPersonnel: 'Janet Roslene Beloro (MW)',
    philHealthSupported: true,
    distanceKm: 4.2,
    baseCost: 'Free',
    currentCongestion: 20,
    waitingTimeMinutes: 15,
    contactNumber: '0961-607-3195',
    operatingHours: 'Mon-Fri 8AM-5PM',
    location: { lat: 13.6758, lng: 123.2441 }
  },
  {
    id: 'bhs-carolina',
    name: 'Carolina Barangay Health Station',
    type: 'BHC',
    services: ['Daily Consultation', 'Prenatal Day', 'HIV Screening', 'Immunization', 'NTP'],
    specializedServices: ['Teenage Pregnancy Counseling', 'Women\'s Day (VIA/Breast Exam)', 'Mental Health Counseling'],
    contactPersonnel: 'BHS Carolina Staff',
    philHealthSupported: true,
    distanceKm: 6.5,
    baseCost: 'Free',
    currentCongestion: 12,
    waitingTimeMinutes: 8,
    contactNumber: '0946-360-4591',
    operatingHours: 'Mon-Fri 8AM-5PM',
    location: { lat: 13.6858, lng: 123.2541 }
  },
  {
    id: 'bhs-concepcion-grande',
    name: 'Concepcion Grande BHS',
    type: 'BHC',
    services: ['Daily Consultation', 'NTP Day', 'Immunization', 'Prenatal Day'],
    specializedServices: ['Adolescent Health', 'Mental Health Consultation', 'Women\'s Day (VIA)', 'Medical Check-up', 'Dental Check-up'],
    contactPersonnel: 'Rosa M. Paa (MW)',
    philHealthSupported: true,
    distanceKm: 2.8,
    baseCost: 'Free',
    currentCongestion: 33,
    waitingTimeMinutes: 18,
    contactNumber: '0992-646-0324',
    operatingHours: 'Mon-Fri 8AM-5PM',
    location: { lat: 13.6198, lng: 123.2091 }
  },
  {
    id: 'bhs-concepcion-pequena',
    name: 'Concepcion Pequeña BHS',
    type: 'BHC',
    services: ['Family Planning', 'Adolescent Health', 'Maternal Health Care', 'National TB Program'],
    specializedServices: ['Dental Extraction', 'Dog and Cat Vaccination', 'HPV Vaccination', 'Nutrition Services', 'Leprosy Prevention'],
    contactPersonnel: 'Neliza G. Diaz (RN)',
    philHealthSupported: true,
    distanceKm: 2.4,
    baseCost: 'Free',
    currentCongestion: 40,
    waitingTimeMinutes: 22,
    contactNumber: '0945-162-8425',
    operatingHours: 'Mon-Fri 8AM-5PM',
    location: { lat: 13.6258, lng: 123.2041 }
  },
  {
    id: 'bhs-del-rosario',
    name: 'Del Rosario Barangay Health Station',
    type: 'BHC',
    services: ['Daily Consultation', 'NTP Enrollment', 'YAKAP Profiling', 'Medicine Dispensing'],
    specializedServices: ['Adolescent Counseling', 'Dental Extraction', 'Growth Monitoring', 'Home Visits'],
    contactPersonnel: 'Jose Peñas III',
    philHealthSupported: true,
    distanceKm: 3.1,
    baseCost: 'Free',
    currentCongestion: 25,
    waitingTimeMinutes: 15,
    contactNumber: '0917-183-8392',
    operatingHours: 'Mon-Fri 8AM-5PM',
    location: { lat: 13.6058, lng: 123.2141 }
  },
  {
    id: 'bhs-pacol',
    name: 'Pacol Barangay Health Station',
    type: 'BHC',
    services: ['Daily Consultation', 'Family Planning', 'Nutrition', 'Immunization', 'Prenatal Day'],
    specializedServices: ['Adolescent Health', 'HIV Testing', 'VIA Screening'],
    contactPersonnel: 'Marilyn Osabal (MW)',
    philHealthSupported: true,
    distanceKm: 5.2,
    baseCost: 'Free',
    currentCongestion: 10,
    waitingTimeMinutes: 5,
    contactNumber: '0907-656-2472',
    operatingHours: 'Mon-Fri 8AM-5PM',
    location: { lat: 13.6658, lng: 123.2341 }
  },
  {
    id: 'bhs-sabang',
    name: 'Sabang Barangay Health Station',
    type: 'BHC',
    services: ['Daily Consultation', 'TB Day', 'Immunization', 'Prenatal Day'],
    specializedServices: ['WATSAN Services', 'Adolescent Consultation', 'IUD Referral', 'Operation Timbang'],
    contactPersonnel: 'Louie Bombales (MW)',
    philHealthSupported: true,
    distanceKm: 0.8,
    baseCost: 'Free',
    currentCongestion: 60,
    waitingTimeMinutes: 40,
    contactNumber: '0931-990-8974',
    operatingHours: 'Mon-Fri 8AM-5PM | Sat-Sun 9AM-3PM',
    location: { lat: 13.6188, lng: 123.1851 }
  },
  {
    id: 'bhs-tinago',
    name: 'Tinago Barangay Health Station',
    type: 'BHC',
    services: ['Daily Consultation', 'Family Planning', 'NTP Enrollment', 'YAKAP Profiling'],
    specializedServices: ['Adolescent Consultation', 'Dental Check-up', 'PSI Insertion', 'VIA Screening'],
    contactPersonnel: 'Sarah Mae B. Osorio (MW)',
    philHealthSupported: true,
    distanceKm: 0.5,
    baseCost: 'Free',
    currentCongestion: 35,
    waitingTimeMinutes: 20,
    contactNumber: '0919-581-4731',
    operatingHours: 'Mon-Fri 8AM-5PM',
    location: { lat: 13.6238, lng: 123.1881 }
  },
  {
    id: 'bhs-san-isidro',
    name: 'San Isidro Barangay Health Station',
    type: 'BHC',
    services: ['Daily Consultation', 'Nutrition', 'Prenatal Day', 'Immunization', 'NTP Day'],
    specializedServices: ['Adolescent Day', 'Mental Health Consultation', 'VIA/Breast Cancer Screening', 'Dental Check-up'],
    contactPersonnel: 'Remedios C. Malanyaon (MW)',
    philHealthSupported: true,
    distanceKm: 4.8,
    baseCost: 'Free',
    currentCongestion: 15,
    waitingTimeMinutes: 10,
    contactNumber: '0910-983-3870',
    operatingHours: 'Mon-Fri 8AM-5PM',
    location: { lat: 13.6058, lng: 123.1641 }
  }
];
